name: Main

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
      - name: Create dist zip
        id: gradle
        run: ./gradlew :cli:shadowDistZip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: cli/build/distributions/*.zip
